import type { Metadata } from "next";
import { Figtree, Inter } from "next/font/google";
import "./globals.css";
import MenuHeader from "./components/layout/MenuHeader";
import Footer from "./components/layout/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vital Signs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable} ${figtree.variable}`}>
      <body>
        <MenuHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
