import type { Metadata } from "next";
import { Figtree, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable} ${figtree.variable}`}>
      <body>
        <header className="text-black">
          <div className="">
            <span className="text-lg font-bold">Logo</span>
            <nav className="flex gap-4 text-sm text-slate-300">
              <a href="#beneficios">Benefícios</a>
              <a href="#planos">Planos</a>
              <a href="#contato">Contato</a>
            </nav>
          </div>
        </header>
        {/* Conteúdo do body */}
        {children}
      </body>
    </html>
  );
}
